export const actionTypes = {
  UPSERT_JOB: 'UPSERT_JOB',
  UPDATE_SUBTITLES: 'UPDATE_SUBTITLES',
  FLAG_FOR_REVIEW: 'FLAG_FOR_REVIEW',
  UPDATE_ISSUE: 'UPDATE_ISSUE',
  SAVE_JOB: 'SAVE_JOB',
  TOGGLE_PAIR_COMPLETION_STATUS: 'TOGGLE_PAIR_COMPLETION_STATUS',
  PAIR_COMPLETION_STATUS_PENDING: 'PAIR_COMPLETION_STATUS_PENDING',
  UPDATE_GAP_MARK: 'UPDATE_GAP_MARK',
  UPDATE_EAGLE_MARK: 'UPDATE_EAGLE_MARK',
  UPDATE_GAP_MARK_DIRECTLY: 'UPDATE_GAP_MARK_DIRECTLY',
  UPDATE_EAGLE_MARK_DIRECTLY: 'UPDATE_EAGLE_MARK_DIRECTLY',
  UPDATE_PARAGRAPH_MARK: 'UPDATE_PARAGRAPH_MARK',
};
